PidFile=/tmp/zabbix_server.pid
SocketDir=/tmp
TmpDir=/tmp
AlertScriptsPath=/usr/lib/zabbix/alertscripts
ExternalScripts=/usr/lib/zabbix/externalscripts
FpingLocation=/usr/sbin/fping
Fping6Location=
SSHKeyLocation=
